on:
  push:
    branches:
      - dev
      - stage
      - prod

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.7.3"

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./${{ github.ref_name }}

      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan
        working-directory: ./${{ github.ref_name }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ secrets.TF_VAR_region }}
