name: Terraform Dev CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

working-directory: ./dev

env:
  TF_VERSION: "1.7.3" # Set to the version of Terraform you're using
  TF_VAR_key_pair: ${{ secrets.TF_VAR_key_pair }}

jobs:
  terraform:
    name: Terraform Workflow
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform Code
        run: terraform validate

      - name: Plan Terraform Changes
        run: terraform plan -out=tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ secrets.TF_VAR_region }}

      - name: Apply Terraform Changes (only on main)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ secrets.TF_VAR_region }}
